package ING2projet.LaGuilde.model;

// default package
// Generated Jan 1, 2021 3:02:50 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.format.annotation.DateTimeFormat;


/**
 * Evenement generated by hbm2java
 */
@Entity
public class Evenement  {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	private String titre;
	private String description;
	private String image;
	@DateTimeFormat(pattern ="yyyy-MM-dd")
	private Date date;
	private Integer nbParticipant;
	private int visible;


	public Evenement() {
	}

	public Evenement(Integer id, String titre, String description, String image, Date date, Integer nbParticipant, int visible, int idcreator) {
		this.id = id;
		this.titre = titre;
		this.description = description;
		this.image = image;
		this.date = date;
		this.nbParticipant = nbParticipant;
		this.visible = visible;
		
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Integer getNbParticipant() {
		return this.nbParticipant;
	}

	public void setNbParticipant(Integer nbParticipant) {
		this.nbParticipant = nbParticipant;
	}

	public int getVisible() {
		return this.visible;
	}

	public void setVisible(int visible) {
		this.visible = visible;
	}





	public Evenement id(Integer id) {
		this.id = id;
		return this;
	}

	public Evenement titre(String titre) {
		this.titre = titre;
		return this;
	}

	public Evenement description(String description) {
		this.description = description;
		return this;
	}

	public Evenement image(String image) {
		this.image = image;
		return this;
	}

	public Evenement date(Date date) {
		this.date = date;
		return this;
	}

	public Evenement nbParticipant(Integer nbParticipant) {
		this.nbParticipant = nbParticipant;
		return this;
	}

	public Evenement visible(int visible) {
		this.visible = visible;
		return this;
	}



	@Override
	public boolean equals(Object o) {
		if (o == this)
			return true;
		if (!(o instanceof Evenement)) {
			return false;
		}
		Evenement evenement = (Evenement) o;
		return Objects.equals(id, evenement.id) && Objects.equals(titre, evenement.titre) && Objects.equals(description, evenement.description) && Objects.equals(image, evenement.image) && Objects.equals(date, evenement.date) && Objects.equals(nbParticipant, evenement.nbParticipant) && visible == evenement.visible;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, titre, description, image, date, nbParticipant, visible);
	}

	@Override
	public String toString() {
		return "{" +
			" id='" + getId() + "'" +
			", titre='" + getTitre() + "'" +
			", description='" + getDescription() + "'" +
			", image='" + getImage() + "'" +
			", date='" + getDate() + "'" +
			", nbParticipant='" + getNbParticipant() + "'" +
			", visible='" + getVisible() + "'" +
			"}";
	}
	

}
