package ING2projet.LaGuilde.model;

import java.util.Objects;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// Generated Jan 1, 2021 3:02:50 PM by Hibernate Tools 5.2.12.Final

/**
 * Participants generated by hbm2java
 */
@Entity
public class Participants {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	private int idmembre;
	private int idevent;

	public Participants() {
	}

	public Participants(int idmembre, int idevent) {
		this.idmembre = idmembre;
		this.idevent = idevent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIdmembre() {
		return this.idmembre;
	}

	public void setIdmembre(int idmembre) {
		this.idmembre = idmembre;
	}

	public int getIdevent() {
		return this.idevent;
	}

	public void setIdevent(int idevent) {
		this.idevent = idevent;
	}

	@Override
	public boolean equals(Object o) {
		if (o == this)
			return true;
		if (!(o instanceof Participants)) {
			return false;
		}
		Participants participants = (Participants) o;
		return Objects.equals(id, participants.id) && idmembre == participants.idmembre
				&& idevent == participants.idevent;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, idmembre, idevent);
	}

	@Override
	public String toString() {
		return "{" + " id='" + getId() + "'" + ", idmembre='" + getIdmembre() + "'" + ", idevent='" + getIdevent() + "'"
				+ "}";
	}

}
