package fr.eisti.ACCEG.jee.LeCoinPhoto.model;
// Generated Dec 27, 2021, 3:37:26 PM by Hibernate Tools 5.4.14.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Categories generated by hbm2java
 */
@Entity
public class Categories implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	private String categorie;
	private String icone;

	public Categories() {
	}

	public Categories(String categorie, String icone) {
		this.categorie = categorie;
		this.icone = icone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public String getIcone() {
		return this.icone;
	}

	public void setIcone(String icone) {
		this.icone = icone;
	}

}
