package fr.eisti.ACCEG.jee.LeCoinPhoto.model;
// Generated Dec 25, 2021, 5:00:09 PM by Hibernate Tools 5.4.14.Final

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private Integer id;
	private String categorie;
	private String icone;

	public Categories() {
	}

	public Categories(String categorie, String icone) {
		this.categorie = categorie;
		this.icone = icone;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public String getIcone() {
		return this.icone;
	}

	public void setIcone(String icone) {
		this.icone = icone;
	}

}
