package fr.eisti.ACCEG.jee.LeCoinPhoto.model;
// Generated Dec 25, 2021, 5:00:09 PM by Hibernate Tools 5.4.14.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "Produits")
public class Produits implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name="ID")
	private Integer id;
	
	@Column(name="categorie")
	private String categorie;
	
	@Column(name="reference")
	private String reference;
	
	@Column(name="image")
	private String image;
	
	@Column(name="Nom")
	private String nom;
	
	@Column(name="description")
	private String description;
	
	@Column(name="prix")
	private float prix;
	
	@Column(name="stock")
	private int stock;

	public Produits() {
	}

	public Produits(String categorie, String reference, String image, String nom, String description, float prix,
			int stock) {
		this.categorie = categorie;
		this.reference = reference;
		this.image = image;
		this.nom = nom;
		this.description = description;
		this.prix = prix;
		this.stock = stock;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public float getPrix() {
		return this.prix;
	}

	public void setPrix(float prix) {
		this.prix = prix;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

}
