package fr.eisti.ACCEG.jee.LeCoinPhoto.model;
// Generated Dec 25, 2021, 5:00:09 PM by Hibernate Tools 5.4.14.Final

import java.util.Date;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String prenom;
	private String sexe;
	private Date naissance;
	private String email;
	private String login;
	private String pwd;
	private String panier;
	private String statut;

	public Utilisateurs() {
	}

	public Utilisateurs(String nom, String prenom, String sexe, Date naissance, String email, String login, String pwd,
			String panier, String statut) {
		this.nom = nom;
		this.prenom = prenom;
		this.sexe = sexe;
		this.naissance = naissance;
		this.email = email;
		this.login = login;
		this.pwd = pwd;
		this.panier = panier;
		this.statut = statut;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getSexe() {
		return this.sexe;
	}

	public void setSexe(String sexe) {
		this.sexe = sexe;
	}

	public Date getNaissance() {
		return this.naissance;
	}

	public void setNaissance(Date naissance) {
		this.naissance = naissance;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getPanier() {
		return this.panier;
	}

	public void setPanier(String panier) {
		this.panier = panier;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

}
